- name: Install DB
  hosts: database-vm
  become: true
  
  roles:
    - { role: mysql, tags: [mysql] }

- name: Install nginx
  hosts: nginx
  become: true
  
  roles:
    - { role: nginx, tags: [nginx] }
    - { role: php, tags: [php] }


- name: Install wordpress
  hosts: wordpress
  become: true
  vars_files:
    - vars/wordpress.yml

  roles:
    - { role: wordpress, tags: [wordpress] }

- name: Install haProxy
  hosts: haproxy-vm
  become: true
  
  roles:
    - { role: haproxy, tags: [haproxy] }

  post_tasks:
    - name: Restart php
      ansible.builtin.systemd:
        name: php{{ php_version }}-fpm
        state: restarted
        enabled: true

    - name: Restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true
        
