all: # группа по умолчанию
  children: # указываем, что это вложенные хосты
    geek: # задаём имя группы, может быть любым
      hosts: #
        localhost: # указываем ip или FQDN
    prod:
      hosts:
        10.100.10.45:
          ansible_user: valera
          php_webserver_daemon: "nginx"
          php_default_version_debian: "7.4"
