---
- name: Install php
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - "php{{ php_version }}-fpm"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-xml"
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-readline"
    - "php{{ php_version }}-bz2"
    - "php{{ php_version }}-zip"
    - "php{{ php_version }}-opcache"

- name: Replace php.ini
  ansible.builtin.template:
    src: php.ini.j2
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    owner: root
    group: root
    mode: "0644"
